

---

regionalize:

  datasets:
    - name: carbon dioxide, 1 bar, from post-combustion capture in a coal power plant
      reference product: carbon dioxide, coal
    - name: carbon dioxide, 1 bar, from direct air capture (DAC)
      reference product: carbon dioxide, DAC
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen, from wet poplar biomass with carbon capture and storage (CCS)
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with nuclear, pressure water reactor, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with hydro, reservoir, non-alpine region, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with wind, >3MW turbine, onshore, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with wind, 1-3MW turbine, onshore, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with solar, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with hydro, run-of-river, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with hydro, reservoir, non-alpine region, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with electricity mix, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with hydro, reservoir, alpine region, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with wind, >3MW turbine, onshore, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with wind, 1-3MW turbine, onshore, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with nuclear, pressure water reactor, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with wind, 1-3MW turbine, offshore, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with hydro, pumped storage, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen, from wet poplar biomass with carbon capture and storage (CCS)
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with electricity mix, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with hydro, pumped storage, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from direct air capture (DAC)--hydrogen production, PEM electrolysis powered with wind, 1-3MW turbine, offshore, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with hydro, run-of-river, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with hydro, reservoir, alpine region, included PEM electrolyser construction
      reference product: diesel production
    - name: diesel production,--carbon dioxide, 1 bar, from post-combustion capture in a coal power plant--hydrogen production, PEM electrolysis powered with solar, included PEM electrolyser construction
      reference product: diesel production
    - name: Cooling Water 20-25
      reference product: Cooling Water 20-25
    - name: gasket construction for 1 kg of PEMWE cell stack
      reference product: gasket construction for 1 kg of PEMWE cell stack
    - name: PTFE for nafion membrane construction
      reference product: PTFE for nafion membrane construction
    - name: PEM Electrolyser construction for the production of hydrogen
      reference product: PEM Electrolyser construction for the production of 1 kg electrolytic hydrogen
    - name: Nafion cast membrane construction
      reference product: Nafion cast membrane construction
    - name: CO2 stored in aquifer at 200 km distance from emission source and transported by pipeline
      reference product: CO2 stored in aquifer at 200 km distance from emission source and transported by pipeline
    - name: hydrogen production, from wet poplar biomass with carbon capture and storage (CCS)
      reference product: Hydrogen, gaseous, 25 bar
    - name: wet poplar biomass
      reference product: wet poplar biomass
    - name: hydrogen production, from wet poplar biomass with carbon capture and storage (CCS)
      reference product: Hydrogen, gaseous, 25 bar



# `production pathways` lists the different technologies
production pathways:

  electrolysis_PEM_grid:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with electricity mix, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_hydro_pumped_storage:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with hydro, pumped storage, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_hydro_reservoir_alpine:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with hydro, reservoir, alpine region, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_hydro_reservoir_non_alpine:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with hydro, reservoir, non-alpine region, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_hydro_runofriver:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with hydro, run-of-river, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_nuclear_PWR:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with nuclear, pressure water reactor, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_PV:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with solar, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_wind_onshore1-3:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with wind, 1-3MW turbine, onshore, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_wind_offshore:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with wind, 1-3MW turbine, offshore, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True

  electrolysis_PEM_wind_onshore3:
    production volume:
      variable: Production|Hydrogen|PEM (electricity)
    efficiency:
      - variable: Efficiency|Hydrogen|PEM (electricity)
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
      name: hydrogen production, PEM electrolysis powered with wind, >3MW turbine, onshore, included PEM electrolyser construction
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: False
      regionalize: True
